version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - db
      
  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: