apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.service.databasePort }}
      targetPort: {{ .Values.service.databaseTargetPort }}