apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-vacations-frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: obusorezekiel/dream-vacation-app_frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://dream-vacations-backend-svc"
