{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: default
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.env.secret.POSTGRES_PASSWORD | b64enc }}
{{- end }}
