apiVersion: v1
kind: Service
metadata:
  name: dream-vacations-backend-svc
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.backendPort }}
      targetPort: {{ .Values.backend.backendTargetPort }}
