apiVersion: v1
kind: Service
metadata:
  name: dream-vacations-frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontendPort }}
      targetPort: {{ .Values.service.frontendTargetPort }}
  type: LoadBalancer