apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-vacations-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
        imagePullPolicy: {{ .Values.frontend.pullPolicy }}
        resources:
          limits:
            memory: "{{ .Values.frontend.limits.memory }}"
            cpu: "{{ .Values.frontend.limits.cpu }}"
        ports:
        - containerPort: {{ .Values.frontend.frontendPort }}
        env:
        - name: REACT_APP_API_URL
          value: "{{ .Values.env.frontend.REACT_APP_API_URL }}"
