{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: dream-vacations-frontend-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.frontendPort }}
      targetPort: {{ .Values.frontend.frontendTargetPort }}
  type: LoadBalancer
{{- end }}