apiVersion: apps/v1
kind: Deployment
metadata:
  name: dream-vacations-frontend  # Static name
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://dream-vacations-backend"