name: Backend CI/CD
on:
  push:
    branches: [ main, develop, staging ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-pipeline.yml'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        environment: [dev, staging, prod]
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacations-backend:${{ github.sha }}-${{ matrix.environment }} backend/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacations-backend:${{ github.sha }}-${{ matrix.environment }}

    - name: Deploy to Minikube
      run: |
        minikube status
        eval $(minikube docker-env)
        helm upgrade --install dream-vacations-backend ./helm/dream-vacations \
          --namespace ${{ matrix.environment }} \
          --set backend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/dream-vacations-backend \
          --set backend.image.tag=${{ github.sha }}-${{ matrix.environment }} \
          --set frontend.enabled=false \
          --set database.name=${{ matrix.environment }}_db

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/dream-vacations-backend -n ${{ matrix.environment }}
        kubectl get services -n ${{ matrix.environment }}