name: Backend CI/CD Deployment

on:
  push:
    branches: 
      - main
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yaml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:$SHORT_SHA backend/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:$SHORT_SHA
