name: Backend CI/CD Deployment

on:
  push:
    branches: 
      - main
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yaml'
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  CLUSTER_NAME: k8scluster
  AWS_REGION: us-east-1

jobs:
  configure_aws_credentials:
    name: Configure AWS credentials
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

  build:
    runs-on: ubuntu-latest
    needs: configure_aws_credentials
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:$SHORT_SHA backend/
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:$SHORT_SHA

  scan-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update && sudo apt-get install trivy -y

      - name: Scan Docker image for vulnerabilities
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend:latest

  deploy-to-eks:
    runs-on: ubuntu-latest
    needs: scan-image
    steps:
      - name: checkout-branch
        uses: actions/checkout@v2
  
      - name: Install Kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
  
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Deploy to EKS
        run: |
          if [[ $GITHUB_REF_NAME == 'develop' ]]; then
          NAMESPACE='dev';
          elif [[ $GITHUB_REF_NAME == 'main' ]]; then
            NAMESPACE='prod';
          else
            echo "Unknown branch, deployment skipped.";
            exit 1;
          fi

          helm upgrade --install dream-vacation ./helm/dream-vacation \
          --namespace $NAMESPACE \
          --set backend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_backend \
          --set backend.image.tag=latest \
          --set frontend.enabled=false \
          --set database.enabled=true  



