name: Backend CI/CD
on:
  push:
    branches: [ main, develop, staging ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yaml'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacations-backend:${{ github.sha }} backend/
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacations-backend:${{ github.sha }}
    
    - name: List directory contents
      run: |
        ls -R ./helm
    - name: Rename chart.yaml to Chart.yaml
      run: mv ./helm/dream-vacations/chart.yaml ./helm/dream-vacations/Chart.yaml  
        
    - name: Deploy to Minikube
      run: |
        eval $(minikube docker-env)

        if [[ $GITHUB_REF_NAME == 'develop' ]]; then
          NAMESPACE='dev';
        elif [[ $GITHUB_REF_NAME == 'staging' ]]; then
          NAMESPACE='staging';
        elif [[ $GITHUB_REF_NAME == 'main' ]]; then
          NAMESPACE='prod';
        else
          echo "Unknown branch, deployment skipped.";
          exit 1;
        fi

        helm upgrade --install dream-vacations-backend ./helm/dream-vacations \
          --namespace $NAMESPACE \
          --set frontend.image.repository=${{ secrets.DOCKERHUB_USERNAME }}/dream-vacations-backend \
          --set frontend.image.tag=${{ github.sha }} \
          --set backend.enabled=false \
          --set database.enabled=false

    - name: Cleanup old deployments
      run: |
        # Keep only the 3 most recent deployments
        helm list -q | sort -r | tail -n +4 | xargs -r helm uninstall
    
        # Remove dangling images
        docker image prune - 