name: Frontend CI/CD Deployment

on:
  push:
    branches: 
      - main
      - develop
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-deploy.yaml'
  workflow_dispatch:

jobs:
  build-fe-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
            SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
            docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_frontend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_frontend:$SHORT_SHA frontend/
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_frontend:latest
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/dream-vacation-app_frontend:$SHORT_SHA