apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dream-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: christomesh/dream-app-backend:latest
        ports:
        - containerPort: 3001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: database_url
        - name: COUNTRIES_API_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: countries_api_base_url
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: dream-dev
spec:
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 32001
  selector:
    app: backend
  type: NodePort
