apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dream-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: christomesh/dream-app-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_URL
          value: http://backend:3001
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dream-dev
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: frontend
